app/urls.py
from django.urls import path
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView

urlpatterns = [
    # 一覧画面
    path('',  ItemFilterView.as_view(), name='index'),
    # 一覧画面
    path('result/<int:pk>/', ItemFilterView.as_view(), name='index'),
    # 詳細画面
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    # 登録画面
    path('create/', ItemCreateView.as_view(), name='create'),
    # 更新画面
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    # 削除画面
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.start),
    path('admin/', admin.site.urls),
    path('upload/', views.upload, name='upload'),

    # 一覧画面
    path('index/', include('app.urls')),
]

app/models.py
from django.db import models

class Item(models.Model):
    # TODO: Define fields here
    no = models.IntegerField('no', blank=True, null=True)
    name = models.CharField('name', blank=True, max_length=100)
    CATEGORY = (
        ('0', 'シューター'),
        ('1', 'マニューバー'),
        ('2', 'ブラスター'),
        ('3', 'スピナー'),
        ('4', 'ローラー'),
        ('5', 'フデ'),
        ('6', 'チャージャー'),
        ('7', 'スロッシャー'),
        ('8', 'シェルター'),
        ('9', 'ガイザー'),
    )
    category = models.CharField(blank=True, max_length=2, choices=CATEGORY)
    gauge = models.IntegerField('gauge', blank=True, null=True)
    release_condition = models.CharField('release_condition', blank=True, max_length=100)
    range = models.IntegerField('range', blank=True, null=True)
    continuous_power = models.IntegerField('continuous_power', blank=True, null=True)
    fixed_num = models.IntegerField('fixed_num', blank=True, null=True)
    created_at = models.DateTimeField(
        verbose_name='登録日',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'ブキ'
        verbose_name_plural = 'ブキ一覧'

    def __str__(self):
        return self.name

app/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ('name', 'no', 'category', 'gauge', 'release_condition', 'range', 'continuous_power', 'fixed_num',)
        widgets = {
                    'name': forms.TextInput(),
                    'no': forms.NumberInput(attrs={'min': 1}),
                    'category': forms.RadioSelect(),
                    'gauge': forms.NumberInput(attrs={'min': 0}),
                    'release_condition': forms.NumberInput(attrs={'min': 0}),
                    'range': forms.NumberInput(attrs={'min': 0}),
                    'continuous_power': forms.NumberInput(attrs={'min': 0}),
                    'fixed_num': forms.NumberInput(attrs={'min': 0}),
                  }

app/views.py
from django.shortcuts import render
import csv
from io import TextIOWrapper, StringIO

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from .models import Item
from .filters import ItemFilter
from .forms import ItemForm

def start(self):
    return render(self,'app/_base2.html')

def upload(request):
    if 'csv' in request.FILES:
        form_data = TextIOWrapper(request.FILES['csv'].file, encoding='cp932')
        csv_file = csv.reader(form_data)
        for line in csv_file:
            weapon, created = Item.objects.get_or_create(name=line[1])
            weapon.no = line[0]
            weapon.name = line[1]
            weapon.category = line[2]
            weapon.gauge = line[3]
            weapon.release_condition = line[4]
            weapon.range = line[5]
            weapon.continuous_power = line[6]
            weapon.fixed_num = line[7]
            weapon.save()

        return render(request, 'app/upload.html')

    else:
        return render(request, 'app/upload.html')

# 検索一覧画面
class ItemFilterView(LoginRequiredMixin, FilterView):
    model = Item
    filterset_class = ItemFilter
    # デフォルトの並び順を新しい順とする
    queryset = Item.objects.all().order_by('-created_at')

    # クエリ未指定の時に全件検索を行うために以下のオプションを指定（django-filter2.0以降）
    strict = False

    # 1ページあたりの表示件数
    paginate_by = 10

    # 検索条件をセッションに保存する or 呼び出す
    def get(self, request, **kwargs):
        if request.GET:
            request.session['query'] = request.GET
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]

        return super().get(request, **kwargs)

# 詳細画面
class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item


# 登録画面
class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')


# 更新画面
class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')


# 削除画面
class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    success_url = reverse_lazy('index')

app/templates/app/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>アプリケーション名</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link href="{% static "app/css/app.css" %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">アプリケーション名</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false"
            aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'%}">管理サイト</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:logout'%}">ログアウト</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    {% block content %}
    {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{% static "app/js/plugins/responsive-paginate.js" %}"></script>
    <script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

app/templates/app/_base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css" />
    <title>{% block title %}データベース{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/upload">upload</a></li>
            <li><a href="/index">index</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

app/templates/app/item_card.html
<div class="row">
    <div class="col-3">
        <p>name</p>
    </div>
    <div class="col-9">
        <p>{{ item.name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>no</p>
    </div>
    <div class="col-9">
        <p>{{ item.no }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>category</p>
    </div>
    <div class="col-9">
        <p>{{ item.get_category_display }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>gauge</p>
    </div>
    <div class="col-9">
        <p>{{ item.gauge }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>release_condition</p>
    </div>
    <div class="col-9">
        <p>{{ item.release_condition }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>range</p>
    </div>
    <div class="col-9">
        <p>{{ item.range }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>continuous_power</p>
    </div>
    <div class="col-9">
        <p>{{ item.continuous_power }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>fixed_num</p>
    </div>
    <div class="col-9">
        <p>{{ item.fixed_num }}</p>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <p>登録日</p>
    </div>
    <div class="col-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>

app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
<div class="container">
    <h2 class="text-center">データ削除</h2>
    <p>このデータを削除します。よろしいですか？</p>

    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
        {% include "./item_card.html" %}
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                    <input type="submit" class="btn btn-outline-secondary" value="削除" />
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container">
    <h2 class="text-center">詳細表示</h2>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
        </div>
    </div>
    <!--  -->
    {% include "./item_card.html" %}
    <div class="row">
        <div class="col-12">
            <a class="btn btn-outline-secondary float-right" href="{% url 'index' %}">戻る</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/item_filter.html
{% extends "app/_base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">検索条件</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="filter" method="get">
                    <div class="modal-body">
                        {{filter.form|crispy}}
                    </div>
                </form>
                <div class="modal-footer">
                    <a class="btn btn-outline-secondary" data-dismiss="modal">戻る</a>
                    <button type="submit" class="btn btn-outline-secondary" form="filter">検索する </button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <a class="btn btn-secondary filtered" style="visibility:visible" href="/?page=1">検索を解除</a>
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
            </div>
        </div>
    </div>

    <div class="row" >
        <div class="col-12">
            {% include "app/_pagination.html" %}
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <ul class="list-group">
                {% for item in item_list %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-3">
                            <p>name</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>no</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.no }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>category</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.category }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>gauge</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.gauge }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>release_condition</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.release_condition }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>range</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.range }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>continuous_power</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.continuous_power }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>fixed_num</p>
                        </div>
                        <div class="col-9">
                            <p>{{ item.fixed_num }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <p>登録日</p>
                        </div>
                        <div class="col-9">
                            <p>{{item.created_at|date:"Y/m/d G:i:s"}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="float-right">
                                <a class="btn btn-outline-secondary " href="{% url 'detail' item.pk %}">詳細</a>
                                <a class="btn btn-outline-secondary " href="{% url 'update' item.pk %}">編集</a>
                                <a class="btn btn-outline-secondary " href="{% url 'delete' item.pk %}">削除</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">
                    対象のデータがありません
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row" >
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'create' %}">新規</a>
                <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal" href="#">検索</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/app/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.certifications.errors }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center">データ入力</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <form method="post" id="myform">
                {%crispy form%}
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn btn-outline-secondary" href="{% url 'index' %}">戻る</a>
                <a class="btn btn-outline-secondary save" href="#">保存</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/upload.html
{% load static %}
{% block title %}あなたのデータアップロード{% endblock %}
{% block extrahead %}
<script>
$(function(){
  $('.dropify').dropify();
})
</script>
{% endblock %}

{% block content %}
<h3>アップロードするよ</h3>
<form action="{% url 'upload' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">アップロード</button>
</form>

{% endblock content %}